---
title: "Carnegie Status EDA"
author: 'Rob Lane'
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
carnegie<-read.csv("carnegie.csv",stringsAsFactors = T)
carnegie$Class.num <- factor(carnegie$Class, levels = c("R2","R1"))
carnegie$logexp<-log(carnegie$R.D.expenditures*1000)
# This makes sure we're predicting what else is needed on top of an R2 university to reach R1

head(carnegie)
```
```{r}
library(ggplot2)
ggplot(carnegie, aes(x=Class, y=grad.students)) + geom_boxplot() + 
    xlab("Class") + ylab("Grad Students") + ggtitle("Grad Students by Class")

ggplot(carnegie, aes(x=Class, y=Doctorates)) + geom_boxplot() + 
    xlab("Class") + ylab("Doctorates") + ggtitle("Doctorates by Class")

ggplot(carnegie, aes(x=Class, y=floorspace)) + geom_boxplot() + 
    xlab("Class") + ylab("Floorspace") + ggtitle("Floorspace by Class")

ggplot(carnegie, aes(x=Class, y=logexp)) + geom_boxplot() + 
    xlab("Class") + ylab("log(R&D Expenditures)") + ggtitle("R&D by Class")
```




```{r}

model1<-glm(Class.num~Doctorates+grad.students+Doctorates:grad.students+logexp+floorspace,
            data=carnegie,
            family="binomial")
AIC(model1)
```

```{r}
library(caret)

fitControl <- trainControl(method = "repeatedcv", number = 5, repeats = 1, classProbs = TRUE, summaryFunction = mnLogLoss)

glmnet.fit <- train(Class.num ~ poly(Doctorates, 2) + poly(grad.students, 2) + Doctorates:grad.students + logexp + floorspace,
                    data = carnegie,
                    method = "glmnet",
                    trControl = fitControl,
                    metric = "logLoss")

coef(glmnet.fit$finalModel, glmnet.fit$finalModel$lambdaOpt)

library(pROC)
model <- glm(Class.num~poly(Doctorates,2)+poly(grad.students,2)+logexp,data=carnegie)
simple.predprobs<-predict(carnegie,model,type="response")
simple.roc<-roc(response=carnegie$Class,predictor=simple.predprobs,levels=c("R2","R1"))
plot(simple.roc)

```






